### ISSUE TITLE
IP / Domain

### ISSUE THREAD

**Issue by darkiop** [braindead1/ioBroker.robonect#18]
Aktuell kann man in der Adapter Konfiguration nur eine IP Adresse, bzw. einen Hostnamen mit einer begrenzten Anzahl an Zeichen einstellen. Hier wäre es schön wenn man auch einen FQDN eintragen kann, z.B. robonect.mein-heim-netzwerk.de

**Comment by braindead1** [comment]
Fixed with e7513d0.
