### ISSUE TITLE
Polling done message fills the log file

### ISSUE THREAD

**Issue by Galileo53** [braindead1/ioBroker.robonect#20]
The info message "Polling done" is constantly logged in the IoBroker log file, e.g. every minute what is the default configuration.
This will fill the log file very soon, so that other log messages are almost invisible or even swapped out.
Suggestion: Make this logging configurable or even easier: change the log level from this.log.info('Polling done') to this.log.debug('Polling done');

**Comment by braindead1** [comment]
Fixed in 6e49247.
