### ISSUE TITLE
Exception thrown with FW 1.07a

### ISSUE THREAD

**Issue by FKuypers** [braindead1/ioBroker.robonect#3]
Hi, 

I am trying to use your adapter with my H30X module on a Gardena R40li. There seems to be an exception thrown with ever poll:

`

host.Atom-NUC | 2019-04-28 09:56:32.681 | error | instance system.adapter.robonect.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-04-28 09:56:32.681 | error | by controller[0]: at processTicksAndRejections (internal/process/next_tick.js:76:17)
Caught | 2019-04-28 09:56:32.681 | error | by controller[0]: at endReadableNT (_stream_readable.js:1129:12)
Caught | 2019-04-28 09:56:32.681 | error | by controller[0]: at IncomingMessage.emit (events.js:202:15)
Caught | 2019-04-28 09:56:32.681 | error | by controller[0]: at Object.onceWrapper (events.js:285:13)
Caught | 2019-04-28 09:56:32.681 | error | by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:1083:12)
Caught | 2019-04-28 09:56:32.680 | error | by controller[0]: at Request.emit (events.js:197:13)
Caught | 2019-04-28 09:56:32.680 | error | by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:1161:10)
Caught | 2019-04-28 09:56:32.680 | error | by controller[0]: at Request.emit (events.js:197:13)
Caught | 2019-04-28 09:56:32.680 | error | by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:185:22)
Caught | 2019-04-28 09:56:32.680 | error | by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/robonect.js:4182:86)
Caught | 2019-04-28 09:56:32.680 | error | by controller[0]: TypeError: Cannot read property 'enable' of undefined
robonect.0 | 2019-04-28 09:56:32.633 | info | cleaned everything up...
robonect.0 | 2019-04-28 09:56:32.632 | error | at processTicksAndRejections (internal/process/next_tick.js:76:17)
robonect.0 | 2019-04-28 09:56:32.632 | error | at endReadableNT (_stream_readable.js:1129:12)
robonect.0 | 2019-04-28 09:56:32.632 | error | at IncomingMessage.emit (events.js:202:15)
robonect.0 | 2019-04-28 09:56:32.632 | error | at Object.onceWrapper (events.js:285:13)
robonect.0 | 2019-04-28 09:56:32.632 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:1083:12)
robonect.0 | 2019-04-28 09:56:32.632 | error | at Request.emit (events.js:197:13)
robonect.0 | 2019-04-28 09:56:32.632 | error | at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:1161:10)
robonect.0 | 2019-04-28 09:56:32.632 | error | at Request.emit (events.js:197:13)
robonect.0 | 2019-04-28 09:56:32.632 | error | at Request.self.callback (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:185:22)
robonect.0 | 2019-04-28 09:56:32.632 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/robonect.js:4182:86)
robonect.0 | 2019-04-28 09:56:32.632 | error | TypeError: Cannot read property 'enable' of undefined
robonect.0 | 2019-04-28 09:56:32.632 | error | uncaught exception: Cannot read property 'enable' of undefined
robonect.0 | 2019-04-28 09:56:31.551 | error | Error: socket hang up
robonect.0 | 2019-04-28 09:56:31.549 | error | Error: socket hang up
robonect.0 | 2019-04-28 09:56:31.448 | info | Polling done (Initial)
robonect.0 | 2019-04-28 09:56:30.972 | info | Done
robonect.0 | 2019-04-28 09:56:30.897 | info | starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.robonect, node: v11.8.0

`

Any idea how to fix it?

Thanks,

Frank

**Comment by FKuypers** [comment]
This happens, when the internal AP of Robonect is switched off... if you switch it on, the exception goes away.

Frank

**Comment by braindead1** [comment]
Hi Frank,

I'm sorry, but the development of ioBroker.robonect has been deprecated in favour of using the build in MQTT feature in Robonect.

Please feel free to take over the development in case MQTT is not the desired solution for you.

Markus

**Comment by darkiop** [comment]
Hallo Markus, kannst du dein Robonect MQTT Skript hier posten?
