### ISSUE TITLE
Keine Verbindung mit Robonect Applikation V1.1b

### ISSUE THREAD

**Issue by Prastoj** [braindead1/ioBroker.robonect#7]
Hallo,

Mein Robonect HX hat die Version 1.1b
Ich kann keine Verbindung halten mit dem Adapter.
Die Werte sind kurz da, der Adapter wird aber sofort Rot und die Verbindung bricht ab.

Ich denke man muss den Adapter auf die neue Version updaten?

`

host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | instance system.adapter.robonect.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1129:12)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:1083:12)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:1161:10)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/iobroker.robonect/node_modules/request/request.js:185:22)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/robonect.js:4071:77)
host.ioBroker-RasPi4 | 2019-11-17 21:38:43.771 | error | Caught by controller[0]: TypeError: Cannot read property 'quality' of undefined
robonect.0 | 2019-11-17 21:38:43.661 | error | Error: read ECONNRESET
robonect.0 | 2019-11-17 21:38:43.659 | error | Error: read ECONNRESET
robonect.0 | 2019-11-17 21:38:43.656 | error | Error: read ECONNRESET
robonect.0 | 2019-11-17 21:38:43.655 | error | Error: read ECONNRESET
robonect.0 | 2019-11-17 21:38:43.650 | error | Error: read ECONNRESET
robonect.0 | 2019-11-17 21:38:43.649 | error | Error: read ECONNRESET
robonect.0 | 2019-11-17 21:38:43.641 | error | Error: socket hang up
robonect.0 | 2019-11-17 21:38:43.638 | error | Error: socket hang up

`

**Comment by braindead1** [comment]
Erstmal danke für die Fehlermeldung, auch wenn ich jetzt erst reagiere.

Die Robonect Firmware v1.1b schränkt die Anzahl der gleichzeitigen API Requests ein. Der Adapter muss deshalb so umgebaut werden, dass die Requests nacheinander und nicht gleichzeitig abgesetzt werden.

**Comment by Prastoj** [comment]
Danke für die Antwort. Eine späte ist besser wie keine :)
Hoffe du bekommst das hin.

**Comment by braindead1** [comment]
Das Problem sollte behoben sein. Bitte testen.

**Comment by Prastoj** [comment]
Danke.

Leider keine besserung:


`
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.389 | info | Restart adapter system.adapter.robonect.0 because enabled
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.389 | info | instance system.adapter.robonect.0 terminated with code 0 (NO_ERROR)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.389 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.389 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1129:12)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.388 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.388 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.388 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.388 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.388 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.388 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.387 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.387 | error | Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/robonect.js:4191:81)
host.ioBroker-RasPi4 | 2020-03-15 08:51:36.387 | error | Caught by controller[0]: TypeError: Cannot read property 'quality' of undefined
robonect.0 | 2020-03-15 08:51:35.869 | info | (11056) Terminated (NO_ERROR): Without reason
robonect.0 | 2020-03-15 08:51:35.867 | info | (11056) terminating
robonect.0 | 2020-03-15 08:51:35.826 | info | (11056) cleaned everything up...
robonect.0 | 2020-03-15 08:51:35.823 | error | (11056) TypeError: Cannot read property 'quality' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/robonect.js:4191:81) at Request.self.callback (/opt/iobrok
robonect.0 | 2020-03-15 08:51:35.822 | error | (11056) uncaught exception: Cannot read property 'quality' of undefined
robonect.0 | 2020-03-15 08:51:35.665 | info | (11056) Done
robonect.0 | 2020-03-15 08:51:35.569 | info | (11056) starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.robonect, node: v10.16.0
host.ioBroker-RasPi4 | 2020-03-15 08:51:33.700 | info | instance system.adapter.robonect.0 started with pid 11056
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.570 | info | Restart adapter system.adapter.robonect.0 because enabled
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.569 | info | instance system.adapter.robonect.0 terminated with code 0 (NO_ERROR)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.569 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.569 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1129:12)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.569 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.569 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.569 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.568 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.568 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.568 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.568 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.568 | error | Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/robonect.js:4191:81)
host.ioBroker-RasPi4 | 2020-03-15 08:51:03.567 | error | Caught by controller[0]: TypeError: Cannot read property 'quality' of undefined
robonect.0 | 2020-03-15 08:51:03.051 | info | (10619) Terminated (NO_ERROR): Without reason
robonect.0 | 2020-03-15 08:51:03.050 | info | (10619) terminating
robonect.0 | 2020-03-15 08:51:03.022 | info | (10619) cleaned everything up...
`

**Comment by braindead1** [comment]
Danke fürs Testen. Bei mir läuft der Adapter bisher ohne Probleme, so dass wir mal herausfinden müssen, was genau die Unterschiede zwischen unseren beiden Systemen ist. 

- Lief der Adapter bei Dir in einer alten Version bzw. mit einer alten Firmware?
- Welchen Mähroboter hast Du?
- Welche Versionen von Firmware, WLAN Treiber, ZeroConf sind bei Dir installiert?
- Welche Node.js und NPM Version ist bei Dir installiert?
- Wie ist der Adapter bei Dir konfiguriert?
- Sind der ioBroker und der Mähroboter im selben Netz?

Screenshots würden mir sehr helfen. 

Evtl. spielen einige der obigen Fragen keine Rolle, aber weil ich nicht weiß wo das Problem liegen könnte, müssen wir uns herantasten.

**Comment by Prastoj** [comment]
Hallo, Danke für die rasche Antwort.

Also installiert ist dein Adapter Version 0.0.6

Verbunden mit Host: falsch
Lebenszeichen: falsch
Verbunden mit robonect: wahr

Mein RobonectHX und Roboter:

Bootloader
--
Version: | V1.0
Kompiliert: | 25.07.2019 16:36
Bemerkung: | Release V1.0

WLAN
--
AT-Version: | V1.7.0
SDK-Version: | V3.0.0
Kompiliert: | 03.05.2019

ZeroConf
--
Version: | V1.5
Kompiliert: | 02.10.2019 16:42
Bemerkung: | ZeroConf V1.5

Applikation
--
Version: | V1.1
Kompiliert: | 25.09.2019 08:54
Bemerkung: | V1.1b


Mein Roboter:

Gardena Sileno Life 2019

Gerätekonfiguration
--
Seriennummer: | 190408253
Produktion: | 24.01.2019 08:59

Geräteversion
--
MSW-Software: | P0.2
MSW-Version: | 15.09.00
MSW-Datum: | 2018-11-29 08:49:03
SUB-Version: | 6.05.00


....Ich habe gelesen Gardena hat eine neue Firmware für den Sileno Life rausgebracht.
Spiele ich nachher mal ein, denke aber das wird keine Auswirkung haben

Danke MfG

**Comment by darkiop** [comment]
Bin noch auf der 1.0A vom August 2019 - sieht soweit ganz gut aus. Wechsle Morgen auf die 1.1b und berichte.

**Comment by Prastoj** [comment]
> Bin noch auf der 1.0A vom August 2019 - sieht soweit ganz gut aus. Wechsle Morgen auf die 1.1b und berichte.

Ich habe das Robonect leider erst seit der 1.1b

**Comment by braindead1** [comment]
@Prastoj Ich vermute, dass Du ein Problem mit IP, Benutzername oder Passwort hast. 

- Bei der IP darf kein http:// eingegeben werden.
- Bist Du sicher, dass Benutzername und Passwort stimmen?
- Hat Dein Passwort Sonderzeichen? Falls ja, bitte mal ohne probieren.
- Kannst Du mal bitte posten, was Dir angezeigt wird, wenn Du `http://<USERNAME>:<PASSWORT>@192.168.178.141/json?cmd=status` im Browser aufrufst? USERNAME und PASSWORT natürlich ersetzen durch Deine Daten.

**Comment by Prastoj** [comment]
> * http://<USERNAME>:<PASSWORT>@192.168.178.141/json?cmd=status

Username und Passwort stimmen 100%
Genau dasselbe gebe ich ein wenn ich im Browser "192.168.178.141" aufrufe. Dann komme ich auf die Oberfläche von Robonect.

Keine Sonderzeichen.

Wenn ich
http://<prastoj>:<562347qa>@192.168.178.141/json?cmd=status
im Browser aufrufe, kommt das Anmelde Bild die ganze Zeit ( username und Passwort )
geht aber nicht weg, kann ich nur immer wieder bestätigen, es taucht aber dann wieder auf. Keine Robonect Oberfläche oder so.

![Bildschirmfoto 2020-03-16 um 09 54 31](https://user-images.githubusercontent.com/48070275/76739452-8133b580-676c-11ea-956e-c328675fb8e1.png)
![Bildschirmfoto 2020-03-16 um 09 56 50](https://user-images.githubusercontent.com/48070275/76739458-82fd7900-676c-11ea-9ba7-4417cb8ed79b.png)



Direkt über die IP komme ich auf die Oberfläche.

**Comment by braindead1** [comment]
Meine "Anleitung" war nicht klar genug. Sorry. Bitte versuch den link mal ohne < und >. Die Klammern sollten nur klar machen, dass es sich um einen Platzhalter handelt.

Die Konfiguration des Adapters sieht aber richtig aus. Ob sich Robonect anders verhält abhängig vom Mähroboter?

**Comment by Prastoj** [comment]
Ah sorry. Ich trottel 😂


Hier nochmal :

`` {"name": "Sileno life", "id": "D717FE", "status": {"status": 17, "distance": 0, "stopped": false, "duration": 1735, "mode": 0, "battery": 100, "hours": 66}, "timer": {"status": 2, "next": {"date": "2020-03-16", "time": "12:00:00", "unix": 1584360000}}, "wlan": {"signal": -82}, "health": {"temperature": 25, "humidity": 26}, "clock": {"date": "2020-03-16", "time": "10:41:09", "unix": 1584355269}, "successful": true}

**Comment by creecool** [comment]
Hallo,
habe heute auch die Version 0.6 installiert und seit dem o.g. Problem im Log stehen -
Bei p://<USERNAME>:<PASSWORT>@192.168.XX.XX/json?cmd=status erhalte ich die Ausgabe wie bei Prastoj. (natürlich mit anderen Werten) 

Ich habe einen Gardena R70LI / Roboconnect 1.1.b
Raspi4 / iObroker Admin 4.0.4

**Comment by braindead1** [comment]
@Prastoj und @creecool Der Adapter läuft bei mir und anderen User ohne Probleme. Ich tippe also darauf, dass es sich um ein Netzwerkproblem handelt und die Verbindung vielleicht wieder gekappt wird bevor die Antwort komplett übertragen wurde. Ich gucke mal, ob ich das Timeout der Requests verlängern kann.

**Comment by Prastoj** [comment]
Danke.

Kann ichir echt nicht erklären, mein Netz ist sehr einfach gestrickt. Habe nichts außergewöhnliches. Alles im selben gateway. Selbes WLAN/LAN. Einlog Daten sehr einfach....

**Comment by braindead1** [comment]
@Prastoj Dein Problem scheint dasselbe zu sein wie #11. Der Fehler sollte behoben sein. Bitte den Adapter einmal aktualisieren und testen.

**Comment by Prastoj** [comment]
> @Prastoj Dein Problem scheint dasselbe zu sein wie #11. Der Fehler sollte behoben sein. Bitte den Adapter einmal aktualisieren und testen.


Leider nicht :(

`

host.ioBroker-RasPi4 | 2020-03-17 18:36:01.337 | info | Restart adapter system.adapter.robonect.0 because enabled
-- | -- | -- | --
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.336 | info | instance system.adapter.robonect.0 terminated with code 0 (NO_ERROR)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.335 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.334 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1204:12)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.334 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:323:22)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.333 | error | Caught by controller[0]: at Object.onceWrapper (events.js:417:28)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.333 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.332 | error | Caught by controller[0]: at Request.emit (events.js:311:20)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.331 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.331 | error | Caught by controller[0]: at Request.emit (events.js:311:20)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.330 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.329 | error | Caught by controller[0]: at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/library.js:462:90)
host.ioBroker-RasPi4 | 2020-03-17 18:36:01.318 | error | Caught by controller[0]: TypeError: Cannot read property 'enable' of undefined
robonect.0 | 2020-03-17 18:36:00.765 | info | (621) Terminated (NO_ERROR): Without reason
robonect.0 | 2020-03-17 18:36:00.764 | info | (621) terminating
robonect.0 | 2020-03-17 18:36:00.679 | info | (621) cleaned everything up...
robonect.0 | 2020-03-17 18:36:00.677 | error | (621) TypeError: Cannot read property 'enable' of undefined at Request._callback (/opt/iobroker/node_modules/iobroker.robonect/lib/library.js:462:90) at Request.self.callback (/opt/iobroker/no
robonect.0 | 2020-03-17 18:36:00.676 | error | (621) uncaught exception: Cannot read property 'enable' of undefined
robonect.0 | 2020-03-17 18:35:54.070 | info | (621) Done
robonect.0 | 2020-03-17 18:35:54.024 | info | (621) starting. Version 0.0.7 in /opt/iobroker/node_modules/iobroker.robonect, node: v12.16.1

`

**Comment by braindead1** [comment]
Robonect gibt anscheinend abhängig vom Mähroboter und/oder den gemachten Einstellungen unterschiedliches JSON zurück. 

Kannst Du bitte http://ROBONECTIP/json?cmd=wlan im Browser aufrufen und posten, was Dir angezeigt wird? ROBONECTIP natürlich durch durch die richtige IP ersetzen.

**Comment by Prastoj** [comment]
{"ap": {"enable": false, "mac": "62-01-94-D7-17-FE"}, "station": {"enable": true, "mac": "60-01-94-D7-17-FE", "signal": -84, "ssid": "FRITZ!Box 7580 YO", "password": "********", "dhcp": false, "ping": false, "ip": "192.168.178.141", "netmask": "255.255.255.0", "gateway": "192.168.178.1"}, "successful": true}



Danke für deine Mühe :)

**Comment by braindead1** [comment]
Ich habe den Code gerade angepasst. Kannst Du bitte nochmal testen?

**Comment by Prastoj** [comment]
Scheint zu laufen jetzt. super. vielen Dank!

![Bildschirmfoto 2020-03-17 um 20 53 29](https://user-images.githubusercontent.com/48070275/76896154-9bb37f00-6891-11ea-8dcb-87a48d4f8e85.png)

`

robonect.0 | 2020-03-17 20:54:18.503 | info | (11794) Polling done (Status)
-- | -- | -- | --


`

**Comment by braindead1** [comment]
Erstmal vielen Dank für das Testen! 

Wie schon geschrieben, gibt Robonect abhängig vom Mähroboter und/oder den gemachten Einstellungen unterschiedliches JSON zurück. 

Im ersten Fall fehlte in Deinem JSON die Information über die Messer und deren Qualität. Im zweiten Fall hast Du den Access Point deaktiviert und deshalb fehlen die die Informationen über den Access Point.

**Comment by creecool** [comment]
Hi braindead1 - Problem ist mit der Version 0.8 behoben - Vielen Dank für den Support!!!!!!
